[package]
name       = "tendermint-light-client"
version    = "0.17.0"
edition    = "2018"
license    = "Apache-2.0"
readme     = "README.md"
keywords   = ["blockchain", "bft", "consensus", "cosmos", "tendermint"]
repository = "https://github.com/informalsystems/tendermint-rs"
authors    = [
  "Sean Braithwaite <sean@informal.systems>",
  "Ethan Buchman <ethan@coinculture.info>",
  "Ismail Khoffi <Ismail.Khoffi@gmail.com>",
  "Romain Ruetschi <romain@informal.systems>",
  "Alexander Simmerl <a.simmerl@gmail.com>",
]

description = """
    Implementation of the Tendermint Light Client Verification Protocol.
"""

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["rpc-client"]
rpc-client = ["tokio", "tendermint-rpc/http-client"]
secp256k1 = ["tendermint/secp256k1", "tendermint-rpc/secp256k1"]

[dependencies]
tendermint = { version = "0.17.0", path = "../tendermint" }
tendermint-rpc = { version = "0.17.0", path = "../rpc", default-features = false }

anomaly = { version = "0.2.0", features = ["serializer"] }
contracts = "0.4.0"
crossbeam-channel = "0.4.2"
derive_more = "0.99.5"
futures = "0.3.4"
serde = "1.0.106"
serde_cbor = "0.11.1"
serde_derive = "1.0.106"
sled = "0.34.3"
static_assertions = "1.1.0"
thiserror = "1.0.15"
tokio = { version = "0.2", optional = true }

[dev-dependencies]
tendermint-testgen = { path = "../testgen"}

serde_json = "1.0.51"
gumdrop = "0.8.0"
rand = "0.7.3"
