[package]
name        = "tmkms"
description = "Tendermint Key Management System"
version     = "0.4.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Ismail Khoffi <Ismail.Khoffi@gmail.com>"]
license     = "Apache-2.0"
homepage    = "https://github.com/tendermint/kms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "ed25519", "kms", "key-management", "yubihsm"]
edition     = "2018"

[workspace]
members = [".", "tendermint-rs"]

[badges]
circle-ci = { repository = "tendermint/kms" }

[dependencies]
abscissa = "0.0.6"
abscissa_derive = "0.0.2"
byteorder = "1.2"
bytes = "0.4"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
hkdf = "0.7"
hmac = "0.7"
lazy_static = "1"
prost-amino = "0.4.0"
prost-amino-derive = "0.4.0"
rand_os = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
sha2 = "0.8"
signal-hook = "0.1.7"
signatory = { version = "0.11.1", features = ["ed25519", "ecdsa"] }
signatory-dalek = "0.11"
signatory-secp256k1 = "0.11"
signatory-ledger-tm = { version = "0.11", optional = true }
subtle-encoding = { version = "0.3", features = ["bech32-preview"] }
tendermint = { version = "0.3", path = "tendermint-rs" }
tiny-bip39 = "0.6"
yubihsm = { version = "0.22", features = ["setup", "usb"], optional = true }
zeroize = "0.5"

[dev-dependencies]
tempfile = "3"
rand = "0.6" # TODO: switch to the getrandom crate

[features]
default = []
softsign = []
ledgertm = ["signatory-ledger-tm"]
yubihsm-mock = ["yubihsm/mockhsm"]

# Enable integer overflow checks in release builds for security reasons
[profile.release]
overflow-checks = true
