[workspace]

members = [
    "abci",
    "light-client",
    "light-client-js",
    "p2p",
    "pbt-gen",
    "proto",
    "rpc",
    "tendermint",
    "test",
    "testgen"
]

exclude = [
    "proto-compiler",
    "stainless"
]
