[package]
name        = "tmkms"
description = "Tendermint Key Management System"
version     = "0.6.0-rc1"
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Ismail Khoffi <Ismail.Khoffi@gmail.com>"]
license     = "Apache-2.0"
homepage    = "https://github.com/tendermint/kms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "ed25519", "kms", "key-management", "yubihsm"]
edition     = "2018"

[workspace]
members = [".", "tendermint-rs"]

[badges]
circle-ci = { repository = "tendermint/kms" }

[dependencies]
abscissa_core = "0.2"
atomicwrites = "0.2"
byteorder = "1.2"
bytes = "0.4"
chrono = "0.4"
failure = "0.1"
gumdrop = "0.6"
hkd32 = { version = "0.1.2", default-features = false }
hkdf = "0.7"
hmac = "0.7"
lazy_static = "1"
log = "0.4"
prost-amino = "0.4.0"
prost-amino-derive = "0.4.0"
rand_os = "0.1"
rpassword = { version = "3", optional = true }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
sha2 = "0.8"
signal-hook = "0.1.7"
signatory = { version = "0.12", features = ["ed25519", "ecdsa"] }
signatory-dalek = "0.12"
signatory-secp256k1 = "0.12"
signatory-ledger-tm = { version = "0.12", optional = true }
subtle = "2"
subtle-encoding = { version = "0.3", features = ["bech32-preview"] }
tiny-bip39 = "0.6"
wait-timeout = "0.2"
yubihsm = { version = "0.26", features = ["setup", "usb"], optional = true }
zeroize = "0.9"

[dependencies.tendermint]
version = "0.10"
path = "tendermint-rs"
features = ["amino-types", "config", "secret-connection"]

[dev-dependencies]
tempfile = "3"
rand = "0.7"

[dev-dependencies.abscissa_core]
version = "0.2"
features = ["testing"]

[features]
default = []
softsign = []
ledgertm = ["signatory-ledger-tm"]
yubihsm-mock = ["yubihsm/mockhsm"]
yubihsm-server = ["yubihsm/http-server", "rpassword"]

# Enable integer overflow checks in release builds for security reasons
[profile.release]
overflow-checks = true

[package.metadata.docs.rs]
all-features = true
