[package]
name       = "tendermint"
version    = "0.10.0" # Also update `html_root_url` in lib.rs when bumping this
license    = "Apache-2.0"
homepage   = "https://www.tendermint.com/"
repository = "https://github.com/tendermint/kms/tree/master/crates/tendermint"
readme     = "README.md"
categories = ["cryptography", "database"]
keywords   = ["blockchain", "bft", "consensus", "cosmos", "tendermint"]
edition    = "2018"

description = """
    Tendermint is a high-performance blockchain consensus engine that powers
    Byzantine fault tolerant applications written in any programming language.
    This crate provides core types for representing information about Tendermint
    blockchain networks, including chain information types, secret connections,
    and remote procedure calls (JSONRPC).
    """

authors = [
    "Ismail Khoffi <Ismail.Khoffi@gmail.com>",
    "ValarDragon <dojha12@gmail.com>",
    "Tony Arcieri <tony@iqlusion.io>",
    "Thane Thomson <thane@interchain.io>"
]

[badges]
circle-ci = { repository = "tendermint/kms" }

[dependencies]
byteorder = { version = "1.2", optional = true }
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
digest = "0.8"
failure = "0.1"
hkdf = { version = "0.7", optional = true }
hyper = { version = "0.10", optional = true }
prost-amino = { version = "0.4.0", optional = true }
prost-amino-derive = { version = "0.4.0", optional = true }
rand_os = { version = "0.1", optional = true }
ring = { version = "0.14", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }
signatory = { version = "0.12", features = ["ed25519", "ecdsa"] }
signatory-dalek = { version = "0.12", optional = true }
sha2 = { version = "0.8", default-features = false }
subtle = "2"
subtle-encoding = { version = "0.3", features = ["bech32-preview"] }
tai64 = { version = "2", optional = true, features = ["chrono"] }
toml = { version = "0.5", optional = true }
uuid = { version = "0.7", optional = true, default-features = false }
x25519-dalek = { version = "0.5", optional = true, default-features = false, features = ["u64_backend"] }
zeroize = { version = "0.9", optional = true }

[dev-dependencies]
serde_json = "1"

[features]
default = ["serde", "tai64"]
amino-types = ["prost-amino", "prost-amino-derive"]
config = ["serde", "serde_json", "toml", "zeroize"]
keys = ["signatory-dalek"]
rpc = ["hyper", "rand_os", "serde", "serde_json", "uuid"]
secret-connection = [
    "amino-types",
    "byteorder",
    "rand_os",
    "hkdf",
    "ring",
    "signatory-dalek",
    "x25519-dalek",
    "zeroize"
]

[package.metadata.docs.rs]
all-features = true
