[package]
name        = "cosmos-kms"
description = "Key Management System for Cosmos Validators"
version     = "0.0.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
license     = "Apache-2.0"
homepage    = "https://github.com/tendermint/kms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "kms", "key-management"]

[badges]
circle-ci = { repository = "tendermint/kms" }

[dependencies]
bincode = "1"
clear_on_drop = "0.2"
failure = "0.1"
failure_derive = "0.1"
gumdrop = "0.4"
gumdrop_derive = "0.4"
log = "0.4"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
signatory = "0.5.1"
simplelog = "0.5"
toml = "0.4"
yubihsm = { version = "0.8", optional = true }
sha2 = "^0.7"
hkdf = "^0.5"
amino = { git = "https://github.com/tendermint/amino_rs", branch = "master"}
ring = "^0.12"
serde_json = "1.0"
hex = "0.3.2"
bytes = "0.4"
chrono = "0.4.2"
byteorder = "^1.2"
x25519-dalek = "^0.1"

[features]
dalek-provider = ["signatory/dalek-provider"]
default = ["dalek-provider"]
yubihsm-provider = ["signatory/yubihsm-provider"]
yubihsm-mockhsm = ["yubihsm-provider", "yubihsm/mockhsm"]
