version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:201804050 # bump cache keys when modifying this
    environment:
      # NOTE: RUST_NIGHTLY_VERSION is set in the Dockerfile
      - CARGO_FEATURES: dalek-provider,yubihsm-mockhsm
      - RUSTFLAGS: -Ctarget-feature=+aes
      - RUST_BACKTRACE: full

    steps:
      - checkout
      - restore_cache:
          key: cache-201804050 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustfmt --version
            rustup run $RUST_NIGHTLY_VERSION cargo fmt -- --write-mode=diff
      - run:
          name: clippy
          command: |
            rustup run $RUST_NIGHTLY_VERSION cargo clippy --version
            rustup run $RUST_NIGHTLY_VERSION cargo clippy --verbose --features=$CARGO_FEATURES
      - run:
          name: build (nightly, all features)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version --verbose
            rustup run $RUST_NIGHTLY_VERSION cargo --version --verbose
            rustup run $RUST_NIGHTLY_VERSION cargo build --features=$CARGO_FEATURES
      - run:
          name: test (nightly, all features)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version --verbose
            rustup run $RUST_NIGHTLY_VERSION cargo --version --verbose
            rustup run $RUST_NIGHTLY_VERSION cargo test --features=$CARGO_FEATURES
      - save_cache:
          key: cache-201804050 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
