version: 2

jobs:
  build:
    docker:
    - image: tendermint/kms:build-2019-01-25-v0 # bump cache keys when modifying this
    steps:
    - checkout
    - restore_cache:
        key: cache-2019-01-25-v0 # bump save_cache key below too
    - run:
        name: rustfmt
        command: |
          cargo fmt --version
          cargo fmt -- --check
    - run:
        name: clippy
        command: |
          cargo clippy --version
          cargo clippy --all-features
    - run:
        name: build
        command: |
          rustc --version
          cargo --version
          cargo build --features=yubihsm
          cargo build --features=ledgertm
          cargo build --features=yubihsm,ledgertm,softsign
    - run:
        name: build --release
        command: |
          rustc --version
          cargo --version
          cargo build --release --features=yubihsm
          cargo build --release --features=ledgertm
    - run:
        name: test --all-features
        command: |
          rustc --version
          cargo --version
          cargo test --all --all-features
    - run:
        name: audit
        command: |
          cargo audit --version
          cargo audit
    - run:
        name: validate against test harness
        command: |
          cargo build --features=softsign
          TMKMS_BIN=./target/debug/tmkms sh tests/support/run-harness-tests.sh
    - save_cache:
        key: cache-2019-01-25-v0 # bump restore_cache key above too
        paths:
        - "~/.cargo"
        - "./target"
