[package]
name = "tendermint-lite"
version = "0.1.0"
authors = ["Ethan Buchman <ethan@coinculture.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tendermint = { path = "../tendermint" }
tokio = "0.2"
