[package]
name = "tendermint-testgen"
version = "0.1.0"
authors = ["Andrey Kuprianov <andrey@informal.systems>"]
edition = "2018"

[dependencies]
tendermint = { version = "0.16.0", path = "../tendermint" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ed25519-dalek = "1"
gumdrop = "0.8.0"
simple-error = "0.2.1"

[[bin]]
name = "tendermint-testgen"
path = "bin/tendermint-testgen.rs"
